version: '3.3'

services:
  pg:
    container_name: postgres-db
    image: postgres
    ports:
      - "5888:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - demo-app-network
  app:
    container_name: app
#    image: app:v5
    build:
     dockerfile: Dockerfile
    networks:
      - demo-app-network
    ports:
      - "8081:8081"
    depends_on:
      - pg

volumes:
  db_data: { }

networks:
  demo-app-network:
